In [6]:
import pandas as pd
from sklearn.tree import DecisionTreeClassifier

model = DecisionTreeClassifier()

X= kd.drop

,id,'age','bp','sg','al','su','rbc','pc','pcc','ba',...,'wbcc','rbcc','htn','dm','cad','appet','pe','ane','class',Unnamed: 26
0,1,48,80,1.02,1,0,?,normal,notpresent,notpresent,...,7800,5.2,yes,yes,no,good,no,no,ckd,NaN
1,2,7,50,1.02,4,0,?,normal,notpresent,notpresent,...,6000,?,no,no,no,good,no,no,ckd,NaN
2,3,62,80,1.01,2,3,normal,normal,notpresent,notpresent,...,7500,?,no,yes,no,poor,no,yes,ckd,NaN
3,4,48,70,1.005,4,0,normal,abnormal,present,notpresent,...,6700,3.9,yes,no,no,poor,yes,yes,ckd,NaN
4,5,51,80,1.01,2,0,normal,normal,notpresent,notpresent,...,7300,4.6,no,no,no,good,no,no,ckd,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,396,55,80,1.02,0,0,normal,normal,notpresent,notpresent,...,6700,4.9,no,no,no,good,no,no,notckd,NaN
396,397,42,70,1.025,0,0,normal,normal,notpresent,notpresent,...,7800,6.2,no,no,no,good,no,no,notckd,NaN
397,398,12,80,1.02,0,0,normal,normal,notpresent,notpresent,...,6600,5.4,no,no,no,good,no,no,notckd,NaN
398,399,17,60,1.025,0,0,normal,normal,notpresent,notpresent,...,7200,5.9,no,no,no,good,no,no,notckd,NaN
399,400,58,80,1.025,0,0,normal,normal,notpresent,notpresent,...,6800,6.1,no,no,no,good,no,no,notckd,NaN